### ISSUE TITLE
Select with object values (MUI)

### ISSUE THREAD

**Issue by Hyperkid123** [data-driven-forms/react-forms#1276]
### Discussed in https://github.com/data-driven-forms/react-forms/discussions/1275

<div type='discussions-op-text'>

<sup>Originally posted by **MonaMayrhofer** June 22, 2022</sup>
Hello everyone!

I have skimmed through the online docs and at some points, it is implied that one can use objects as the values for options, like so:
```javascript
      options: [
        {
          label: "A",
          value: {
            code: "a-code",
            blub: "bla",
          },
        },
        ...others
      ],
```
which seems to work fine for single selection, but as soon I enable `isMulti` things start to go very wrong.

First i suddenly have to supply 
```javascript
      initialValue: [],
      clearedValue: [],
```
or else MUIs `useAutocomplete` complains that `Uncaught TypeError: (intermediate value).filter is not a function`

then it seems to work fine, but MUI complains that no "option is equal to the value" which makes sense, as it has no way to know how to compare arbitrary options and some features do not work and the console is spammed with MUIs warnings, so I also add

```javascript
      isOptionEqualToValue: (a, b) => {
        return a.value.code === b?.code;
      },
```

which gets passed through to MUI and fixes this issue. (This is also a problem with single selectors and in the docs btw [here](https://data-driven-forms.org/provided-mappers/select?mapper=mui&schema=basic)) 

Then things start to work more like expected (as long as there is never more than 1 option selected), however as soon as I start to select more than one options this happens:

The first options looses its label and the `b` in `isOptionEqualToValue` gets undefined.

I debugged a bit and found out that the [`getSelectValue`](https://github.com/data-driven-forms/react-forms/blob/4ee53c6dac6727b55be7d4814050fb198be6e43d/packages/common/src/select/select.js#L11) function gets passed the following `stateValue`:

```javascript
[
 {code: "a-code", blub: "bla"},
{label: "B", {code: "b-code", blub: "bloob"},
]
```

which seems kind of messed up.

Before I dig deeper into the codebase I thought I'd check in here, if there is something i have missed or if this is even a known issue.

Thanks y'all

Edit:
Ok I did dig deeper and I suspect that [`handleSelectOption`](https://github.com/data-driven-forms/react-forms/blob/4ee53c6dac6727b55be7d4814050fb198be6e43d/packages/common/src/select/select.js#L36) is the culprit, and kind of "unwraps" the selected options into their values, and so they slowly get "thinner and thinner"</div>

cc [MonaMayrhofer](https://github.com/MonaMayrhofer)

**Comment by MonaMayrhofer** [comment]
Also using `simpleValue` or not doesn't seem to make a difference - the docs state [here](https://data-driven-forms.org/provided-mappers/component-api#select) that it should not be used with `isMulti`

**Comment by MonaMayrhofer** [comment]
If I am correct we would need a way to differentiate between "old values" that have already been mapped the new option that was just added on [this line](https://github.com/data-driven-forms/react-forms/blob/4ee53c6dac6727b55be7d4814050fb198be6e43d/packages/common/src/select/select.js#L56)

**Comment by MonaMayrhofer** [comment]
Sure, I am just using this project since yesterday so I am not yet suuuper familiar with the codebase but I'll see what I can do

**Comment by Hyperkid123** [comment]
We appreciate any help as @rvsia and I are very busy most of the time. Let me know if you need any help. You can follow this guide to set up the local development: https://data-driven-forms.org/development-setup

**Comment by MonaMayrhofer** [comment]
I created some unit tests for the common-module select with object values, and they seem completely fine, so the problem has to indeed lie within the MUI mapper... I now suspect this line [here](https://github.com/MonaMayrhofer/react-forms/blob/4ee53c6dac6727b55be7d4814050fb198be6e43d/packages/mui-component-mapper/src/select/select.js#L49) is the real culprit. It just assumes "if it's an object, then it automatically is the right format, and we don't need to re-wrap it as a value..." 

I'll add some tests to the MUI mapper now and see if they fail.

**Comment by MonaMayrhofer** [comment]
This fails:
```javascript
const option = [
  { id: '789', text: 'foo' },
  { id: '123', text: 'bar' },
];

expect(createValue(option, true)).toEqual([{ value: { id: '789', text: 'foo' } }, { value: { id: '123', text: 'bar' } }]);

```

Which is reasonable, as there is no way of knowing whether an "object" is already a DDF select value in the [`createValue`](https://github.com/MonaMayrhofer/react-forms/blob/4ee53c6dac6727b55be7d4814050fb198be6e43d/packages/mui-component-mapper/src/select/select.js#L47) helper.

I now need some input from you folks on how we should proceed... Some possibilities that come to my mind:

#### Expect `value` field inside of the option
Instead of testing if the supplied options is an object like it is currently done:
```javascript
option.map((item) => (typeof item === 'object' ? item : { value: item }))
```
we could check if it already has a `value` field - which would be a very straight forward fix, but would result in even more cryptic cornercases when someone tries to supply options that contain values that in turn contain a value field...

#### Some shenanigans with marking the options as DDF select values 
E.g injecting a symbol field into them somewhere further up the chain... That would mitigate the weird value corner cases but ... feels somewhat hacky.....

#### Just remove the functionality that createValue adds
This sounds the most promising to me, but I don't have enough insight into the reasoning why createValue exists in the first place to judge...

We can just assume that every value that is passed into `createValue` is the value of a DDF selected option anyways and wrap it in `{value: ...}` regardless of its form.

**Comment by Hyperkid123** [comment]
@MonaMayrhofer The value as object is very project dependent. What I would probably do is allow the developers to define the `createValue` function and by extension omit it. It would go in line with **Just remove the functionality that createValue adds**. You could pass through the option without any change. Alternatively, we could add another prop. Something like `skipCreateValue`. But that might not be sufficient for all the use cases.

We need the `createValue` function and can't just skip it.

We can pass through all the necessary flags, mainly `isMulti` and `simpleValue` to help with the decision.

**Comment by MonaMayrhofer** [comment]
I would now go with passing simpleValue through to `createValue` function, and then changing the check in `createValue` from `typeof item === 'object' ? item : { value: item }` to `simpleValue ? { value: item } :  item` 

If my understanding of what exactly `simpleValue` does is correct at least ^^

**Comment by Hyperkid123** [comment]
Simple value extracts the `value` key from the `option` so in the state you only have the value instead of the whole option.

Passing the simple value to `createValue` is probably something that should have been there from the start.

**Comment by MonaMayrhofer** [comment]
Actually that all was not true.

`createValue` always gets options as an array of form 

```javascript
[
  {label: "bla", value: ...},
  {label: "blub", value: ...},
]
```

regardless of `simpleValue`.

So we can scratch that. 

As far as I understand it now, the option that `createValue` receives is always exactly in the format of the options, so `{label: .., value: ....}`. 
I do not think it receives "raw" values that have to be wrapped in `{value: ...}` at all - Please correct me if I am wrong. 

The real problem probably is that [`parseInternalValue`](https://github.com/data-driven-forms/react-forms/blob/4ee53c6dac6727b55be7d4814050fb198be6e43d/packages/common/src/select/parse-internal-value.js#L7) "unwraps" the old elements, so that just the values are passed to the autocomplete, but if a new value is added it always is in object `{label:.., value:..}` form. 

That is the reason why the check, if it is an object, is in there, to "re-wrap" the old values - but if the unwrapped object also is an object, the check fails and therefore object-values are just unwrapped without being rewrapped.

Why are the values unwrapped via `parseInternalValues` anyways? Can we just skip that for multi-selects?

**Comment by MonaMayrhofer** [comment]
One implication of just skipping parseInternalValues for multi-selects (or all selects) would be that the API when someone wants to pass `isOptionEqualToValue` to the MUI select changes

Until now the first value was in the format `{label: ..., value: ...}` and the second value was just the raw value. (Which is somewhat counterintuitive IMO)

```javascript
isOptionEqualToValue: (a, b) => {
  return a.value === b;
},
```

**Comment by Hyperkid123** [comment]
> Why are the values unwrapped via parseInternalValues anyways? Can we just skip that for multi-selects? It does seem to work when quickly testing it out...

Because we did not wanted to allow select value to be anything other than a Primitive type. I remember having that conversation way back when we did not have advanced select components. The rationale was that it is impossible to do so with a plain HTML `option` tag.

So if skipping the parsing I something you require to achieve the desired result, we can definitely add a configuration option to do so. That would be a new prop that would be false by default. We have to preserve current behavior to avoid regressions.

**Comment by MonaMayrhofer** [comment]
Hahahahaha o gosh, yes I understand why so many projects don't support complex select values in the first place - because its a pain. I was so hyped when I found out that react-forms at least don't explicitly NOT support it.

I don't think I should add an option for a hacky solution to a not-really-supported feature - that's just the entrance to maintenance hell. Maybe in the long term, if many people ask for it, another "complex select" component that is designed for that from the start would be the way to go - but for now, I think I will just create a custom mapper in my own project.

**Comment by Hyperkid123** [comment]
> I think I will just create a custom mapper in my own project

That is usually the preferred option. You can also just create a custom Select component and replace it in the MUI mapper or any other.

**Comment by MonaMayrhofer** [comment]
Sweet!

And many many thanks for the support and all the hard work you people are putting into this project!

**Comment by Hyperkid123** [comment]
Feel free to reach out here or on discord if you need any help with your components. We are always excited to see how are developers using our code.

**Comment by rvsia** [comment]
@MonaMayrhofer So, is there anything we could do for you or could we close this issue? 🙏

**Comment by MonaMayrhofer** [comment]
Oh yea no i believe this can be closed - for the supported use cases everything works like a charm - and for the not supported ones implementing a custom select is as straightforward as can be! :>

Maybe there could be a note somewhere in the docs that object values are not really supported tho ^^
