### ISSUE TITLE
Checkbox component ignoring value, always sending true or false

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#136]
Even if I set a `value` on a checkbox, it sends `true` when it's checked.

**Comment by Hyperkid123** [comment]
Yes? That is how check box works. Values is name of the checkbox.

**Comment by Hyperkid123** [comment]
Well let me correct myself. That is what event.checked returns. And that is what is used for single checkbox.

**Comment by skateman** [comment]
Okay, so you're differing from the HTML specification, I don't think this is a good idea. Also I need the name/value, not the value/true :confused:

**Comment by skateman** [comment]
I understand that you probably need this for the multiple checkboxes, but this is seriously breaking the HTML specs...

**Comment by Hyperkid123** [comment]
We are not redefining anything we just use the checked value which is begin returned from event. Do you want to the whole event to be stored in the form state?

**Comment by skateman** [comment]
I just want this to be consistent with the way a regular HTML form's checkbox would behave. I.e. submitting `[name]: value` instead of `[value]: true`. I get it that this is not doable with a set of checkboxes, but at least for single ones, this should be doable.

**Comment by Hyperkid123** [comment]
I am sorry but i will not be adding this functionality to single checkbox component. If you have single checkbox in your form you expect that something is on/off, yes/no, true/false. In fact from UX perspective I'am constantly told that you should not use single checkbox but switch component instead.

Form submits `[name]: true/false` which was our decision because it matches all the use-cases we uncounted across all the apps that are using ddf and single-checkbox and also every other checkbox component in most react frameworks.

I don't see any point of sending data like `employed: 'yes'` instead of `employed: true`. If there are APIs which expect strings for boolean values I am not really interested to support that kind of design. And there is always the option to create custom component.

**Comment by skateman** [comment]
@Hyperkid123 I don't really care if the component is a switch or a checkbox. However, I don't see how the switch is better if they behave the same way. Or is there a way to send a custom value for a switch? Instead of the `true/false`...
