### ISSUE TITLE
Multi-field validation

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#149]
I noticed in the provider forms, that some of them have a little bit more strict schema than in our current implementation. More specifically, filling the capacity and utilization data is strictly mandatory in them. However, in our current implementation, we make it mandatory only if at least one of the fields in that section is filled out.

Could we do something similar in DDF? Let's say if you fill out a single field in a SUB_FORM, some other fields in that SUB_FORM become mandatory.

cc @Fryguy

**Comment by Hyperkid123** [comment]
There is a form level validation but that requires function which would probably not help here.

If i understand this correctly this is basically conditional validation?

**Comment by skateman** [comment]
Yeah, field A is required if field B or field C are set. Also field B is required if field A or field C are set. Check it out in the current provider form, for example for RHV. The capacity and utilization tab will behave as I described.

**Comment by Hyperkid123** [comment]
When i think about the schema for this i can imagine something like:
```JSX
{
  type: 'required-validator', // type of validator
  condition: {
    when: 'a',
    is: 'something' // we could use existing conditional definitions if it will fit
  }
}
```
> Could we do something similar in DDF? Let's say if you fill out a single field in a SUB_FORM, some other fields in that SUB_FORM become mandatory.

Checking if some field from a SET of fields is filled might require a bit more work. Problem with subform is that its is only a visual separation of some fields, not in the form state. We could theoretically check the schema but since it can be nested (subform inside a subform) we might hit some performance issues.

This could work with scoped fields `address.name` which is form state represented as:
```jsx
{
  address: {
   name: 'foo'
  }
}
```
or `address[0].name`
```jsx
{
  address: [
   {
      name: 'foo'
   }
  ]
}
```
(basically any variations lodash get/set will allow)
That way you can actually reference values from a "partial" of a form. I don't know that would fit current schemas.

> The capacity and utilization tab will behave as I described.

I will check it in a moment.

**Comment by Hyperkid123** [comment]
@skateman ah i see now. So it would basically be:
```jsx
{
  type: 'required-validator',
  condition: {
    when: ['a', 'd', 'e'], // using OR operator
    isNotEmpty: true,
  }
}
```
This should not be a problem let me think about it for a bit.

**Comment by skateman** [comment]
As we can chain validators, this seems as a working alternative. When you have a PR, I'd like to try to model this with the aforementioned C&U form before merging.
