### ISSUE TITLE
PF3: File upload component

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#307]
Just tracking that this is necessary for the provider forms.

**Comment by Hyperkid123** [comment]
This will have to be handled on the renderer level, specifically in field provider in the onChange function.

IF we have an input type of file, we will take the value from `{target: {file}}` and have to build a binary or instance of `FormData`.

**Comment by skateman** [comment]
Any update on this?

**Comment by Hyperkid123** [comment]
I can take a look at a common solution for all mappers.

**Comment by Hyperkid123** [comment]
@skateman so the code changes are very simple. Instead of value, we will store `event.target.files` to the form state. But you will have to handle the submitting on your side.

We just cannot build binaries without knowing how the data is going to be sent. We could encode it into Base64 but that might be the correct format to use for everybody and we can't just use FormData JSON since it will get destroyed when you stringify them.

Currently, the input type file value will have to consist of two parts:
```jsx
{
  inputValue: event.target.value, // metadata fo the input to correctly render
  inputFiles: event.target.files // data to construct the binary from the file
}
```

You will need to then handle the binaries in the submit function. We can make it a bit easier to identify values in state which are actually file values. We can add a list of input names with `input.type === 'file'` so you can easily find them inside the submit values.

Are you OK with that?

**Comment by skateman** [comment]
cc @himdel

**Comment by Hyperkid123** [comment]
@skateman I also assume you are still using V1 of the renderer and mapper?

**Comment by skateman** [comment]
Yes but we're planning on upgrading, right @himdel?

**Comment by Hyperkid123** [comment]
You should we fixed a lot of design mistakes. The biggest "hit" are the schemas because we changed some of the constants. But you can create a bridge between the mappers by just adding components and validators with old keys. The structure is the same. There is a migration guide in the docs.

**Comment by skateman** [comment]
Saw it, seems pretty straightforward to me...
