### ISSUE TITLE
No Field Array mapping for material ui

### ISSUE THREAD

**Issue by dave-calleja** [data-driven-forms/react-forms#421]
**Scope**:
MUI mapper

**Description**
The field array type is not available in the mui mapper and throws an error. Tried using the mapping from patternFly and works well.

**Schema**
For example:
```
{
    fields: [
        {
            component: componentTypes.TEXT_FIELD,
            name: "name",
            label: "Your name"
        },
        {
            component: componentTypes.FIELD_ARRAY,
            fieldKey: "contacts",
            name: "contacts",
            label: "Contacts",
            itemDefault: { type: '', value: '' },
            fields: [
                {
                    component: componentTypes.TEXT_FIELD,
                    name: "type",
                    label: "Type"
                },
                {
                    component: componentTypes.TEXT_FIELD,
                    name: "value",
                    label: "Value"
                }
            ]
        }
    ]
}
```

**Comment by dave-calleja** [comment]
Was considering porting the pf4 mapping to mui and creating a PR. Is there a reason this was not moved over for mui?

**Comment by Hyperkid123** [comment]
@dave-calleja to be honest with you, we just did not think anybody would be interested. We use it in PF in our internal projects but in very limited scenarios. There is also the matter of coming up with a proper design and since we don't use mui mapper we don't have that many resources to spend on it.

If you are interested we can add it to mui mapper, or even better you can create the PR yourself if you want. It would be basically the same as in PF4. @rvsia do you remember if the field array is in the common package?

**Comment by rvsia** [comment]
@Hyperkid123 No, the field array is not in the common. The implementation is simple and designs can be very different, so I see not so many reasons to make it common.

**Comment by Hyperkid123** [comment]
@dave-calleja  We had a quick session and went through the possible designs of the MUI field array and we came up with something like this. Anything is subject to change based on feedback.

Ignore the colors, the main focus here is the layout.

![Component 1](https://user-images.githubusercontent.com/22619452/78897349-50485700-7a72-11ea-9bb8-46d01bae1ff7.png)

If you want, you can start working on PR. Otherwise, either I or @rvsia will start working on it soon.

**Comment by rvsia** [comment]
I am going to work on this.
