### ISSUE TITLE
Fill form values programmatically 

### ISSUE THREAD

**Issue by carlosthe19916** [data-driven-forms/react-forms#664]
**Scope**: Form renderer

**Description**
How to fill the form values programmatically? This is a use case:
I have a Bank Transfer Form that contains multiple fields; the user can fill the fields manually or he can choose to fill the form using templates (previously configured and saved).

In the example above the `initialValues` does not apply since the user can fill the form after the form is initialized and he can fill it with multiple templates.

**Docs**

I've searched in the docs how to accomplish this problem but I couldn't find anything.

**Comment by rvsia** [comment]
Hello.

You can use `useFormApi.change(name, value)` (https://data-driven-forms.org/hooks/use-form-api) function that allows you to set any value you need.

Or you can use `set` conditional action (https://data-driven-forms.org/schema/condition-set).

**Comment by carlosthe19916** [comment]
Sorry for keep bothering you, is there an example somewhere where `useFormApi.change(name, value)` is being used?

**Comment by rvsia** [comment]
@carlosthe19916 no problem, I am glad to help!

I have an example here: https://github.com/RedHatInsights/sources-ui/blob/master/src/components/AddApplication/AuthTypeCleaner.js

This component sets values `authentication` and `selectedAuthentication` to `undefined`, when users change `application-type-id` value. Of course, instead of the undefined, anything can be used. And the `batch` is a function that just takes these two `change` and execute them in a batch, so the form is not rerendered two times, but only one after both changes are made.

**Comment by rvsia** [comment]
@carlosthe19916 Any progress? Can we close this issue if it's okay?

Thanks!

**Comment by carlosthe19916** [comment]
@rvsia Thanks for the feedback and examples provided it worked well, thank you! Yes, we can close this issue.

**Comment by rvsia** [comment]
@carlosthe19916 Awesome, it's great to hear it! :trophy:
