### ISSUE TITLE
Need help: Need to store output to localstorage on field values change

### ISSUE THREAD

**Issue by shashank1010** [data-driven-forms/react-forms#810]
**Scope**: Form Renderer

**Description**
I want to be able to get the current state of the form every time there is a change.
But when i do a getState() in FormSpy the value updates only once. that is when the form state changes from valid to invalid or the other way round.

I want to store the current values to localStorage and for that I need the most recent values irrespective of validation.

I tried hooking onto the change event, unfortunately, that stops the values from being propagated.
Please advice.

**Comment by Hyperkid123** [comment]
@shashank1010 Hi, you can try and add values subscription to the FormSpy component:

```JSX
<FormSpy subscribtion={{values: true}} />
```

**Comment by rvsia** [comment]
@shashank1010 Hello,

you can store values in `debug` function.

https://data-driven-forms.org/components/renderer#optionalprops

```jsx
<FormRenderer
    {...}
    debug={doSomethingOnEachUpdate}
/>
```

**Comment by shashank1010** [comment]
The debug function, would that be safe to be used in production?
Also, I will try to add a subscription. Can a pass a subscriber to the FormSpy? I haven't tried that maybe I should.

**Comment by rvsia** [comment]
@shashank1010 Yeah, the debug just calls a function on each form update, so it's nothing really special.

**Comment by rvsia** [comment]
@shashank1010 You can optimize this approach a little bit further by using the FormSpy together with `onChange` prop. (https://final-form.org/docs/react-final-form/types/FormSpyProps#onchange)

```jsx
<FormSpy subscription={{values: true}} onChange={saveValues} />
```

**Comment by Hyperkid123** [comment]
@shashank1010 @rvsia sorry guys I had a little emergency. Bot suggestions by @rvsia will work. The debug one is a bit "hacky" since its a debug function and should not be really used outside of that purpose but if everything else fails I would go for it.

**Comment by shashank1010** [comment]
Thanks @Hyperkid123 for your inputs.

> @shashank1010 @rvsia sorry guys I had a little emergency. Both suggestions by @rvsia will work. The debug one is a bit "hacky" since its a debug function and should not be really used outside of that purpose but if everything else fails I would go for it.

I have some more findings, with onChange on FormSpy the component is not rendered. And thus it doesn't work. Also if I rendered a separate FormSpy element, the onChange function is still not called.

There are other libraries from FinalForm that expose some more listeners. Will have to try that.

**Comment by Hyperkid123** [comment]
@shashank1010 I was able to ake this work with the form spy check this example:
https://codesandbox.io/s/modest-diffie-pyfzp?file=/src/App.js

Can you send us your code? Maybe we can work out why you have issues with the form spy.

**Comment by Hyperkid123** [comment]
I will close this issue because there was no response for a while. @shashank1010 If you still require any help, feel free to re-open it.

**Comment by fdx-han-xiao** [comment]
Hi, sry to bring it out now again, I am having a related issue when using onChange and FormSpy, my scenario is that:

I use FormSpy and onChange to track the change of the form state, and I have another state outside of the form to do a dynamic validation based on the changed value, which works fine. 

My issue here is that whenever I want to set a state (the validation state I mentioned above, or any other state) in the onChange function, it will rerender the whole form, so that my cursor will loose focus and it will stop me from pressing tab to switch to another field anymore (as the form got rerendered).

I have also tried to use debug and validate, but it will end up with a infinite loop which seems not better than using onChange.

I was wondering if we have any solutions to prevent the form from rerendering in this kind of scenario, much appreciated!
