### ISSUE TITLE
PF3 Date Picker not working

### ISSUE THREAD

**Issue by Maria-Cordero-ibm** [data-driven-forms/react-forms#838]
**Scope**: [date-picker on PF3](https://data-driven-forms.org/mappers/date-picker?mapper=pf3) not working.

**Description**
Date picker produces following error on PF3:
<img width="436" alt="date-picker error" src="https://user-images.githubusercontent.com/71033910/96501318-36a47b00-121e-11eb-8c80-8f9ff54f290a.png">
Error can be reproduced in the [website](https://data-driven-forms.org/mappers/date-picker?mapper=pf3) or loading schema locally.

**Schema**
`export default {`
  `fields: [{`
   `   component: "date-picker",`
    `  label: "Date Picker",`
    ` name: "date-picker"`
    `}]};`

**Comment by Hyperkid123** [comment]
seems like some component names have changed in a recent PF3 release.

**Comment by Hyperkid123** [comment]
@Maria-Cordero-ibm the issue was caused by the latest minor version of `react-day-picker` package. The exports are busted and the component is not actually exported properly. The version was fixated to `7.3.x` until the bug is removed.

Just on a side note, we are thinking about deprecating pf3 mapper because the pf3 project itself is abandoned, and its very difficult to get any support. It will become unusable when the next major release of React happens. And that should not take long.

**Comment by skateman** [comment]
> @Maria-Cordero-ibm the issue was caused by the latest minor version of `react-day-picker` package. The exports are busted and the component is not actually exported properly. The version was fixated to `7.3.x` until the bug is removed.
> 
> Just on a side note, we are thinking about deprecating pf3 mapper because the pf3 project itself is abandoned, and its very difficult to get any support. It will become unusable when the next major release of React happens. And that should not take long.

@Hyperkid123 just a little longer please, we are working on moving towards the carbon mapper...

**Comment by Hyperkid123** [comment]
I know I am just saying that eventually even React won't be able to run PF3.
