### ISSUE TITLE
PF3: text-field with "type: hidden" produces vertical offset

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#879]
![Screenshot from 2020-11-05 10-31-52](https://user-images.githubusercontent.com/649130/98223411-5512b200-1f52-11eb-8a07-5e337473314c.png)

The component below should not cause any visual changes in the form, but as you see it on the screenshot above, it does where the blue mark is.
```
      {
        component: componentTypes.TEXT_FIELD,
        name: 'edit',
        id: 'edit',
        type: 'hidden',
        initialValue: edit,
      },
```

**Comment by Hyperkid123** [comment]
@skateman I believe there is still margin/padding of the field form group. This should be easy enough to fix. Do you want to do it?

**Comment by rvsia** [comment]
Why not to use `hideField: true`?

**Comment by Hyperkid123** [comment]
@rvsia that does not matter. It's a bug the field should not have any dimensions.

**Comment by rvsia** [comment]
@Hyperkid123 not sure if it's a bug. We are hiding fields via `hideField` in DDF, `type` is just a spreaded prop and it doesn't make any sense to use it on text-field. Why to use a text-field at all after that? It's a text-field, not a hidden-field. :smile: I think it would be better to implement `HiddenField` than doing some hardcoding checking `type === hidden` in FormGroup components.

**Comment by Hyperkid123** [comment]
I see where you are coming from. We are basically trapped by the `input[type="hidden"]`. I think we should let the design system to decide whether its a bug or not. Let me check the PF3 react playground and see if this is "intended" or not.

**Comment by rvsia** [comment]
@Hyperkid123 Don't forget we are wrapping the components inside `FormGroup` component, so you cannot test the input alone.

**Comment by Hyperkid123** [comment]
I know

**Comment by skateman** [comment]
Are there any side effects if you put both `hideField: true` and `type: hidden` on a component? And can't this be done automatically?

**Comment by Hyperkid123** [comment]
So since PF3 is just styled wrapper of react-bootstrap I will refer to their docs.
The hidden type does not even hide labels, helpers, etc so @rvsia is correct.

@skateman no this won't be done automatically, just use the `hideField`. Type is a component-specific property and the renderer has no clue what it is. It could break other mappers which can adjust its styling. There is no side effect of using `hideField`. It just wraps the element into a div with `display: hidden` (or none I can't recall).

![screenshot-react-bootstrap github io-2020 11 05-10_57_35](https://user-images.githubusercontent.com/22619452/98226052-cdc73d80-1f55-11eb-9e3c-a219c6aad825.png)
